apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: fcp
    app.kubernetes.io/managed-by: kustomize
  name: proxy-service
  namespace: system
spec:
  ports:
    - port: 6443
      protocol: TCP
      targetPort: 6443 
  selector:
    control-plane: controller-manager
    app.kubernetes.io/name: fcp
