---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-tenancy-fcp-funccloud-com-v1alpha1-workspace
  failurePolicy: Fail
  name: mworkspace-v1alpha1.kb.io
  rules:
  - apiGroups:
    - tenancy.fcp.funccloud.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - workspaces
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-workload-fcp-funccloud-com-v1alpha1-application
  failurePolicy: Fail
  name: mapplication-v1alpha1.kb.io
  rules:
  - apiGroups:
    - workload.fcp.funccloud.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - applications
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-tenancy-fcp-funccloud-com-v1alpha1-workspace
  failurePolicy: Fail
  name: vworkspace-v1alpha1.kb.io
  rules:
  - apiGroups:
    - tenancy.fcp.funccloud.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - workspaces
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-workload-fcp-funccloud-com-v1alpha1-application
  failurePolicy: Fail
  name: vapplication-v1alpha1.kb.io
  rules:
  - apiGroups:
    - workload.fcp.funccloud.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - applications
  sideEffects: None
