apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: le-prod-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: noreply@funccloud.com
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    solvers:
    - http01:
        ingress:
          class: contour-external