---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - serving.knative.dev
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workload.fcp.funccloud.com
  resources:
  - applications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workload.fcp.funccloud.com
  resources:
  - applications/finalizers
  verbs:
  - update
- apiGroups:
  - workload.fcp.funccloud.com
  resources:
  - applications/status
  verbs:
  - get
  - patch
  - update
