apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
featureGates:
  KubeletInUserNamespace: true
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 31080
    hostPort: 80
    listenAddress: "0.0.0.0"  
  - containerPort: 31443
    hostPort: 443
    listenAddress: "0.0.0.0"
  - containerPort: 32443
    hostPort: 6443
    listenAddress: "0.0.0.0"