---
apiVersion: v1
kind: Secret
metadata:
  name: google-oidc-credentials
  namespace: pinniped-supervisor
type: secrets.pinniped.dev/oidc-client
stringData:
  clientID: ""
  clientSecret: ""
---
apiVersion: idp.supervisor.pinniped.dev/v1alpha1
kind: OIDCIdentityProvider
metadata:
  name: google
  namespace: pinniped-supervisor
spec:
  issuer: https://accounts.google.com
  client:
    secretName: google-oidc-credentials
  authorizationConfig:
    additionalScopes: [ "profile", "email" ]
  claims:
    username: email
    groups: groups
---
apiVersion: config.supervisor.pinniped.dev/v1alpha1
kind: FederationDomain
metadata:
  name: fcp-federation-domain
  namespace: pinniped-supervisor
spec:
  issuer: https://id.fcp.funccloud.dev
  tls:
    secretName: pinniped-supervisor-tls-domain
  identityProviders:
  - displayName: Google
    objectRef:
      apiGroup: idp.supervisor.pinniped.dev
      kind: OIDCIdentityProvider
      name: google
---
apiVersion: authentication.concierge.pinniped.dev/v1alpha1
kind: JWTAuthenticator
metadata:
  name: supervisor-authenticator
spec:
  issuer: https://id.fcp.funccloud.dev
  audience: fcp-federation-domain