apiVersion: tenancy.fcp.funccloud.com/v1alpha1
kind: Workspace
metadata:
  labels:
    app.kubernetes.io/name: fcp
    app.kubernetes.io/managed-by: kustomize
  name: workspace-sample
spec:
  # TODO(user): Add fields here
