apiVersion: tenancy.fcp.funccloud.com/v1alpha1
kind: Workspace
metadata:
  labels:
    app.kubernetes.io/name: fcp
    app.kubernetes.io/managed-by: kustomize
  name: felipe
spec:
   type: personal # The type of the workspace.
   owners:
    - name: felipe # The name of the owner (User or Group).
      kind: User
